ASFLAGS_ADDITIONAL = -march=armv7-a -mfloat-abi=hard -mfpu=neon
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2016b/toolbox/target/SUPPOR~1/BEAGLE~1
STACK_SIZE = 64
