function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:22,type:"var"};
this.def["OverrunFlag"] = {file: "ert_main_c.html",line:23,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:24,type:"fcn"};
this.def["main"] = {file: "ert_main_c.html",line:41,type:"fcn"};
this.def["Trial2_B"] = {file: "Trial2_c.html",line:23,type:"var"};
this.def["Trial2_DW"] = {file: "Trial2_c.html",line:26,type:"var"};
this.def["Trial2_M_"] = {file: "Trial2_c.html",line:29,type:"var"};
this.def["Trial2_M"] = {file: "Trial2_c.html",line:30,type:"var"};
this.def["Trial2_step"] = {file: "Trial2_c.html",line:33,type:"fcn"};
this.def["Trial2_initialize"] = {file: "Trial2_c.html",line:157,type:"fcn"};
this.def["Trial2_terminate"] = {file: "Trial2_c.html",line:602,type:"fcn"};
this.def["B_Trial2_T"] = {file: "Trial2_h.html",line:62,type:"type"};
this.def["DW_Trial2_T"] = {file: "Trial2_h.html",line:67,type:"type"};
this.def["PIController_I"] = {file: "Trial2_h.html",line:71,type:"var"};
this.def["P_Trial2_T"] = {file: "Trial2_types_h.html",line:24,type:"type"};
this.def["RT_MODEL_Trial2_T"] = {file: "Trial2_types_h.html",line:27,type:"type"};
this.def["Trial2_P"] = {file: "Trial2_data_c.html",line:23,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:30,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:54,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:65,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:89,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:30,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:54,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:28,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:39,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:51,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:57,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:63,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:69,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:40,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:47,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:54,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:73,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:79,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:80,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:81,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:97,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:137,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:144,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:151,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:158,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:179,type:"type"};
this.def["config_ADCA_SOC0"] = {file: "MW_c28xx_adc_c.html",line:8,type:"fcn"};
this.def["config_ADCB_SOC1"] = {file: "MW_c28xx_adc_c.html",line:21,type:"fcn"};
this.def["InitAdcA"] = {file: "MW_c28xx_adc_c.html",line:34,type:"fcn"};
this.def["InitAdcB"] = {file: "MW_c28xx_adc_c.html",line:49,type:"fcn"};
this.def["init_board"] = {file: "MW_c28xx_board_c.html",line:8,type:"fcn"};
this.def["init_eCAN_A"] = {file: "MW_c28xx_can_c.html",line:12,type:"fcn"};
this.def["disableWatchdog"] = {file: "MW_c28xx_csl_c.html",line:8,type:"fcn"};
this.def["enable_interrupts"] = {file: "MW_c28xx_csl_c.html",line:16,type:"fcn"};
this.def["config_ePWM_GPIO"] = {file: "MW_c28xx_pwm_c.html",line:8,type:"fcn"};
this.def["getLoopbackIP"] = {file: "MW_target_hardware_resources_h.html",line:15,type:"var"};
this.def["CAN_DATATYPE_GROUND"] = {file: "can_datatype_ground_c.html",line:4,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["Trial2_c.html"] = "../Trial2.c";
	this.html2Root["Trial2_c.html"] = "Trial2_c.html";
	this.html2SrcPath["Trial2_h.html"] = "../Trial2.h";
	this.html2Root["Trial2_h.html"] = "Trial2_h.html";
	this.html2SrcPath["Trial2_private_h.html"] = "../Trial2_private.h";
	this.html2Root["Trial2_private_h.html"] = "Trial2_private_h.html";
	this.html2SrcPath["Trial2_types_h.html"] = "../Trial2_types.h";
	this.html2Root["Trial2_types_h.html"] = "Trial2_types_h.html";
	this.html2SrcPath["Trial2_data_c.html"] = "../Trial2_data.c";
	this.html2Root["Trial2_data_c.html"] = "Trial2_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_c28xx_adc_c.html"] = "../MW_c28xx_adc.c";
	this.html2Root["MW_c28xx_adc_c.html"] = "MW_c28xx_adc_c.html";
	this.html2SrcPath["MW_c28xx_board_c.html"] = "../MW_c28xx_board.c";
	this.html2Root["MW_c28xx_board_c.html"] = "MW_c28xx_board_c.html";
	this.html2SrcPath["MW_c28xx_can_c.html"] = "../MW_c28xx_can.c";
	this.html2Root["MW_c28xx_can_c.html"] = "MW_c28xx_can_c.html";
	this.html2SrcPath["MW_c28xx_csl_c.html"] = "../MW_c28xx_csl.c";
	this.html2Root["MW_c28xx_csl_c.html"] = "MW_c28xx_csl_c.html";
	this.html2SrcPath["MW_c28xx_pie_h.html"] = "../MW_c28xx_pie.h";
	this.html2Root["MW_c28xx_pie_h.html"] = "MW_c28xx_pie_h.html";
	this.html2SrcPath["MW_c28xx_pwm_c.html"] = "../MW_c28xx_pwm.c";
	this.html2Root["MW_c28xx_pwm_c.html"] = "MW_c28xx_pwm_c.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["can_datatype_ground_c.html"] = "../can_datatype_ground.c";
	this.html2Root["can_datatype_ground_c.html"] = "can_datatype_ground_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","Trial2_c.html","Trial2_h.html","Trial2_private_h.html","Trial2_types_h.html","Trial2_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","MW_c28xx_adc_c.html","MW_c28xx_board_c.html","MW_c28xx_can_c.html","MW_c28xx_csl_c.html","MW_c28xx_pie_h.html","MW_c28xx_pwm_c.html","MW_target_hardware_resources_h.html","can_datatype_ground_c.html"];
